version: "3.7"

services:
    next_app:
        container_name: next_app
        build: .
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        env_file:
            - ./.env
        environment:
            - NODE_ENV=production
            - HOSTNAME=next_app

    proxy:
        container_name: proxy
        build: .
        image: decentralize/caching-proxy
        ports:
            - "8088:80"
        environment:
            - UPSTREAM=http://next_app:3000
            - MAX_SIZE=500m
            - HOSTNAME=proxy