version: "3.7"

services:
    next_app:
        container_name: next_app
        build: .
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        ports:
            - "3000:3000"
        env_file:
            - ./.env
        environment:
            - NODE_ENV=production
            - HOSTNAME=next_app
            - PORT=3000
            - NEXT_TELEMETRY_DISABLED=1

    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
        - next_app